# Generated by Django 5.2.3 on 2025-06-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_checklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(default='Not specified'),
        ),
    ]
