# Generated by Django 5.2.3 on 2025-06-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_request_submitted_at_request_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='clock_out',
            new_name='check_out',
        ),
    ]
